# Generated by Django 5.0.2 on 2024-02-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birtday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('AR', 'Argentinian'), ('BR', 'Brazilian'), ('CO', 'Colombian'), ('CL', 'Chilean'), ('EC', 'Ecuadorian'), ('MX', 'Mexican'), ('PE', 'Peruvian'), ('UY', 'Uruguayan'), ('VE', 'Venezuelan'), ('US', 'American'), ('CA', 'Canadian'), ('USR', 'Russian')], max_length=100, null=True)),
            ],
        ),
    ]
